import { google } from 'googleapis';

const SHEET_ID = '1YXsfIO4r6gC5dUSRSjsFjRm2TwSQoYE5JlLQSNnvE8M';
const EXCLUDED_SHEETS = ['Dashboard', 'Client List', 'Editor List', 'Late Delivery Log'];

// ─────────────────────────────────────────────────────────────────────────────
// Sheet layout (updated 2026 — Samad inserted an ID column at A):
//   A = ID                 (e.g. "January 2026 - 0001", generated by Apps Script)
//   B = Client Name
//   C = Content No
//   D = Content Title
//   E = Video Editor
//   F = Status
//   G = Deadline
//   H = Delivery Status
//   I = Completion Date
//   J = Link to Raw Files   ← OFF-LIMITS for the webapp. Manual smart-chip paste
//                            zone; the Apps Script extracts the link URL into K.
//   K = Hard Links          ← Google Drive links. The webapp reads AND writes K.
// Column numbers below are 1-based (6 = F status, 7 = G deadline, 8 = H delivery,
// 9 = I completion, 10 = J, 11 = K).
// ─────────────────────────────────────────────────────────────────────────────

export function getSheetsClient() {
  const key = JSON.parse(
    Buffer.from(process.env.GOOGLE_SERVICE_ACCOUNT_KEY_B64 || '', 'base64').toString()
  );
  const auth = new google.auth.GoogleAuth({
    credentials: key,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });
  return google.sheets({ version: 'v4', auth });
}

function parseDateStr(s: string): number {
  // Supports: DD-Mmm-YYYY (1-Jul-2026), DD/MM/YYYY, YYYY-MM-DD, or a serial-like string
  const m = s.match(/^(\d{1,2})-([A-Za-z]{3})-(\d{4})$/);
  if (m) {
    const months: Record<string, number> = { jan: 0, feb: 1, mar: 2, apr: 3, may: 4, jun: 5, jul: 6, aug: 7, sep: 8, oct: 9, nov: 10, dec: 11 };
    const mo = months[m[2].toLowerCase()];
    if (mo !== undefined) return new Date(+m[3], mo, +m[1]).getTime();
  }
  const t = Date.parse(s);
  return isNaN(t) ? Number.MAX_SAFE_INTEGER : t;
}

/**
 * Runs the equivalent of the Google Sheets onEdit() Apps Script logic
 * AFTER a service-account (API) write, since API edits don't fire triggers.
 *
 * Mirrors the Apps Script (which is already on the new A=ID layout):
 *  - sortAndRenumber: when Column G (deadline, col=7) changes → sort by G, renumber C
 *  - updateCompletionDate: when Column F (status, col=6) becomes "Done" → set I=today
 *    if empty; when status is cleared → clear I
 *  - checkLateDelivery: when Column H (delivery, col=8) becomes "LATE DELIVERY" → log
 *    to Late Delivery Log (keyed by unique ID in column A)
 */
export async function runOnEditLogic(
  tabName: string,
  row: number,
  col: number, // 1-based column (6 = F status, 7 = G deadline, 8 = H delivery)
  value: string | null,
): Promise<void> {
  if (EXCLUDED_SHEETS.includes(tabName)) return;

  const sheets = getSheetsClient().spreadsheets;

  // ── 1. sortAndRenumber — only when Deadline (G, col 7) changes ──
  if (col === 7) {
    // Read the tab to find how far the data extends (any content in A..K).
    const res = await sheets.values.get({
      spreadsheetId: SHEET_ID,
      range: `'${tabName}'!A2:K1000`,
    });
    const rows = res.data.values || [];
    let last = rows.length;
    while (last > 0) {
      const r = rows[last - 1];
      if (r && r.some((c) => c !== undefined && c !== null && String(c).trim() !== '')) break;
      last--;
    }
    if (last === 0) return;

    // Sort IN PLACE via a sortRange request. IMPORTANT: a previous clear+rewrite
    // flattened =HYPERLINK formulas and stripped native cell links — the values API
    // only reads/writes plain values, so links would be lost. Moving rows in place
    // preserves formulas, smart chips, hyperlinks, and cell formatting (J stays intact).
    const ssMeta = await sheets.get({
      spreadsheetId: SHEET_ID,
      ranges: [`'${tabName}'!A1`],
      fields: 'sheets(properties(sheetId,title))',
    });
    const grid = ssMeta.data.sheets?.find((s) => s.properties?.title === tabName);
    const sheetId = grid?.properties?.sheetId;
    if (sheetId === undefined) throw new Error(`No grid id for tab ${tabName}`);

    await sheets.batchUpdate({
      spreadsheetId: SHEET_ID,
      requestBody: {
        requests: [{
          sortRange: {
            range: {
              sheetId,
              startRowIndex: 1,        // skip header row
              endRowIndex: last + 1,   // last data row (0-based end)
              startColumnIndex: 0,     // A
              endColumnIndex: 11,      // K (A..K — includes both J and K)
            },
            sortSpecs: [{ dimensionIndex: 6, sortOrder: 'ASCENDING' }], // column G (0-based)
          },
        }],
      },
    });

    // Renumber Column C (Content No) — 1..N for rows with a Client (col B).
    const colBRes = await sheets.values.get({
      spreadsheetId: SHEET_ID,
      range: `'${tabName}'!B2:B${last + 1}`,
    });
    let counter = 1;
    const numbering = (colBRes.data.values || []).map((r) =>
      r[0] && String(r[0]).trim() !== '' ? [String(counter++)] : [''],
    );
    await sheets.values.update({
      spreadsheetId: SHEET_ID,
      range: `'${tabName}'!C2:C${last + 1}`,
      valueInputOption: 'USER_ENTERED',
      requestBody: { values: numbering },
    });
    return; // sorting already handled the write
  }

  // ── 2. updateCompletionDate — Status (F, col 6) ──
  if (col === 6) {
    const dateCell = await sheets.values.get({
      spreadsheetId: SHEET_ID,
      range: `'${tabName}'!I${row}`,
    });
    const current = dateCell.data.values?.[0]?.[0];
    if (value === 'Done' && !current) {
      const today = new Date().toLocaleDateString('en-MY', {
        day: '2-digit', month: 'short', year: 'numeric',
      });
      await sheets.values.update({
        spreadsheetId: SHEET_ID,
        range: `'${tabName}'!I${row}`,
        valueInputOption: 'USER_ENTERED',
        requestBody: { values: [[today]] },
      });
    } else if (!value && current) {
      // Status cleared → clear the completion date (matches Apps Script)
      await sheets.values.update({
        spreadsheetId: SHEET_ID,
        range: `'${tabName}'!I${row}`,
        valueInputOption: 'USER_ENTERED',
        requestBody: { values: [['']] },
      });
    }
  }

  // ── 3. checkLateDelivery — Delivery (H, col 8) becomes "LATE DELIVERY" ──
  if (col === 8 && value === 'LATE DELIVERY') {
    const rowRes = await sheets.values.get({
      spreadsheetId: SHEET_ID,
      range: `'${tabName}'!A${row}:K${row}`,
    });
    const r = rowRes.data.values?.[0] || [];
    const editor = r[4];       // E
    const contentID = r[0];    // A (unique ID)
    const deliveryStatus = r[7]; // H

    if (editor && deliveryStatus === 'LATE DELIVERY' && contentID) {
      // Ensure log sheet exists
      const ss = await sheets.get({ spreadsheetId: SHEET_ID });
      const hasLog = ss.data.sheets?.some((s) => s.properties?.title === 'Late Delivery Log');
      if (!hasLog) {
        await sheets.batchUpdate({
          spreadsheetId: SHEET_ID,
          requestBody: {
            requests: [{ addSheet: { properties: { title: 'Late Delivery Log' } } }],
          },
        });
        await sheets.values.update({
          spreadsheetId: SHEET_ID,
          range: "'Late Delivery Log'!A1:D1",
          valueInputOption: 'USER_ENTERED',
          requestBody: { values: [['Editor', 'Date Flagged', 'Source Sheet', 'Content ID']] },
        });
      }

      // Prevent duplicates
      const logRes = await sheets.values.get({
        spreadsheetId: SHEET_ID,
        range: "'Late Delivery Log'!A2:D1000",
      });
      const alreadyExists = (logRes.data.values || []).some(
        (rec) => rec[0] === editor && rec[2] === tabName && rec[3] === contentID
      );

      if (!alreadyExists) {
        const today = new Date().toLocaleDateString('en-MY', {
          day: '2-digit', month: 'short', year: 'numeric',
        });
        await sheets.values.append({
          spreadsheetId: SHEET_ID,
          range: "'Late Delivery Log'!A:D",
          valueInputOption: 'USER_ENTERED',
          requestBody: { values: [[editor, today, tabName, contentID]] },
        });
      }
    }
  }
}
